openapi: 3.0.0
info:
  title: Process Payment API
  description: This is a API for Processing Payments
  contact:
    email: santhosh.kbr@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:3000
- url: https://virtserver.swaggerhub.com/sbalasa/ProcessPayment/1.0.0
  description: SwaggerHub API
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /ProcessPayments:
    get:
      tags:
      - developers
      summary: Gets Payment Info
      description: |
        Get the Payment Information
      operationId: get_payment_info
      parameters:
      - name: CardHolder
        in: query
        description: pass an optional search string for looking up Card Holder Details
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: skip
        in: query
        description: number of records to skip for pagination
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          format: int32
      - name: limit
        in: query
        description: maximum number of records to return
        required: false
        style: form
        explode: true
        schema:
          maximum: 50
          minimum: 0
          type: integer
          format: int32
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentItem'
                x-content-type: application/json
        "400":
          description: bad input parameter
        "500":
          description: Internal System Error
      x-openapi-router-controller: swagger_server.controllers.developers_controller
    post:
      tags:
      - admins
      summary: Processes Credit Card Payments
      description: Adds an item to the system
      operationId: add_payment_info
      requestBody:
        description: Payment item to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentItem'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal System Error
      x-openapi-router-controller: swagger_server.controllers.admins_controller
components:
  schemas:
    PaymentItem:
      required:
      - Amount
      - CardHolder
      - CreditCardNumber
      - ExpirationDate
      - SecurityCode
      type: object
      properties:
        CreditCardNumber:
          type: string
          example: 5500 0000 0000 0004
        CardHolder:
          type: string
          example: Santee Cooper
        ExpirationDate:
          type: string
          format: date-time
        SecurityCode:
          type: integer
          example: 322
        Amount:
          type: number
          example: 45.32
      example:
        ExpirationDate: 2000-01-23T04:56:07.000+00:00
        Amount: 45.32
        CreditCardNumber: 5500 0000 0000 0004
        CardHolder: Santee Cooper
        SecurityCode: 322

